services: mongodb
language: ruby
before_install: gem install bundler -v='1.11.2'
script: "bundle exec rake spec"
rvm:
  - 2.3.1
env:
  - CODECLIMATE_REPO_TOKEN=f506e465f1ed0571aeaa5e1cb9c14214c9f7567a92d1af70903f3d0bc8015ed6
notifications:
  email: false
addons:
  code_climate:
    repo_token: f506e465f1ed0571aeaa5e1cb9c14214c9f7567a92d1af70903f3d0bc8015ed6